{
 "title": "TaskTimeTracker Metrics",
 "tags": [
  "spring-boot",
  "prometheus",
  "tasktimetracker"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(http_server_requests_seconds_count[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, method) (rate(http_server_requests_seconds_bucket[5m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Отношение Http запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"2..\"}[5m]))",
     "legendFormat": "2xx успешные"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4..\"}[5m]))",
     "legendFormat": "4xx клиентские ошибки"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[5m]))",
     "legendFormat": "5xx серверные ошибки"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}