spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
  security:
    basic:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    ru.cdek.TaskTimeTracker: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{} - %msg%n"